/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
export type TransformationsParams = { limit?: string };

export type AddFieldsOptions = { [key: string]: any };

export type AddFieldsType = typeof AddFieldsType[keyof typeof AddFieldsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddFieldsType = {
  AddFields: "AddFields",
} as const;

/**
 * Transformation which adds field to an output record. The path of the added field can be nested.
 */
export interface AddFields {
  type: AddFieldsType;
  fields: unknown[];
  $options?: AddFieldsOptions;
}

export type AddedFieldDefinitionType =
  typeof AddedFieldDefinitionType[keyof typeof AddedFieldDefinitionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddedFieldDefinitionType = {
  AddedFieldDefinition: "AddedFieldDefinition",
} as const;

/**
 * Defines the field to add on a record
 */
export interface AddedFieldDefinition {
  type: AddedFieldDefinitionType;
  path: string[];
  value: string;
}

/**
 * description
 */
export interface DeclarativeComponentSchema {
  add_fields: AddFields;
}

/**
 * @summary List all transformations
 */
export const transformations = <
  TData = AxiosResponse<DeclarativeComponentSchema>
>(
  params?: TransformationsParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/transformations`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export type TransformationsResult = AxiosResponse<DeclarativeComponentSchema>;
